console.log(Math.pow(2,53))
console.log(Math.abs(-2))
console.log(1 + 2.0)
console.log(3**4)
console.log(Infinity)
console.log(Number.POSITIVE_INFINITY)
console.log(1/0)
console.log(Number.MAX_VALUE)
console.log(Number.MAX_VALUE * 2)
console.log(-1/0)
console.log(0/0)
console.log(NaN === NaN)